"""
Dragonfly Spine — 48-Hour Pre-Operative Surgical Plan Generator
===============================================================
Produces a clean, 2-page clinical PDF for surgeons, ASC staff, and reps.

    Page 1 — Surgical Plan
        Header | Patient block | Alignment parameters
        3-D spine render | Implant table | Rod specification

    Page 2 — Logistics Checklist
        Header | Tray summary | Tray contents table
        Pre-printed checklist | Footer

Usage::

    from src.dragonfly.plan_generator import generate_plan
    from spineoptimizer.core.models import PatientInfo
    from src.dragonfly.implant_predictor import ImplantPredictor
    from src.dragonfly.tray_optimizer import TrayOptimizer

    plan  = ImplantPredictor().predict(...)
    tray  = TrayOptimizer().optimize(plan)
    pdf   = generate_plan(
                patient      = PatientInfo(patient_id="CASE-001", ...),
                implant_plan = plan,
                tray_config  = tray,
                spinopelvic  = {"lumbar_lordosis_deg": 48, ...},
                render_image = arr,          # numpy HxWx3 uint8 or None
                output_path  = Path("plan.pdf"),
            )
"""
from __future__ import annotations

import io
import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

log = logging.getLogger(__name__)

# ── Page geometry (US Letter: 612 × 792 pt) ───────────────────────────────────
PAGE_W, PAGE_H = 612, 792
MARGIN_L, MARGIN_R = 36, 36
MARGIN_T, MARGIN_B = 36, 36
CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R

# ── Brand palette (ReportLab HexColor strings) ────────────────────────────────
C_NAVY   = "#1a2744"   # header bars
C_TEAL   = "#1D9E75"   # positive / reduction highlight
C_AMBER  = "#BA7517"   # warnings / review needed
C_RED    = "#A32D2D"   # critical issues
C_WHITE  = "#FFFFFF"
C_LGRAY  = "#F4F5F7"   # alternating table rows
C_MGRAY  = "#D1D5DB"   # borders / rules
C_DGRAY  = "#6B7280"   # secondary text
C_BLACK  = "#111827"   # primary text


# ── ReportLab helpers ─────────────────────────────────────────────────────────

def _rl():
    """Lazy import of ReportLab — raises ImportError with install hint if absent."""
    try:
        from reportlab.pdfgen import canvas as rl_canvas
        from reportlab.lib.colors import HexColor, white, black, lightgrey
        from reportlab.lib.units import mm
        return rl_canvas, HexColor
    except ImportError:
        raise ImportError(
            "reportlab is required for PDF generation. "
            "Run: pip install reportlab"
        )


def _hex(code: str):
    from reportlab.lib.colors import HexColor
    return HexColor(code)


# ── Drawing primitives ────────────────────────────────────────────────────────

def _header_band(c, title_right: str = "48-Hour Pre-Operative Plan") -> None:
    """Dark navy header bar with logo text (left) and title (right)."""
    from reportlab.lib.colors import HexColor, white
    bh = 44
    c.setFillColor(HexColor(C_NAVY))
    c.rect(0, PAGE_H - bh, PAGE_W, bh, fill=1, stroke=0)

    # Logo text — left
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(MARGIN_L, PAGE_H - 28, "DRAGONFLY SPINE")

    # Subtitle — right
    c.setFont("Helvetica", 9)
    c.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 28, title_right)

    # Rule below header
    c.setStrokeColor(HexColor(C_MGRAY))
    c.setLineWidth(0.5)
    c.line(MARGIN_L, PAGE_H - bh - 2, PAGE_W - MARGIN_R, PAGE_H - bh - 2)


def _footer(c, case_id: str, page: int) -> None:
    """Footer rule + disclaimer + timestamp + case ID."""
    from reportlab.lib.colors import HexColor
    fy = MARGIN_B + 18
    c.setStrokeColor(HexColor(C_MGRAY))
    c.setLineWidth(0.5)
    c.line(MARGIN_L, fy + 10, PAGE_W - MARGIN_R, fy + 10)
    c.setFont("Helvetica", 7)
    c.setFillColor(HexColor(C_DGRAY))
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    c.drawString(MARGIN_L, fy,
                 "Generated by Dragonfly Spine  |  Confidential  |  "
                 "For surgical planning use only — not for patient distribution")
    c.drawRightString(PAGE_W - MARGIN_R, fy,
                      f"Case: {case_id or 'N/A'}  |  {ts}  |  Page {page}")


def _box(c, x: float, y: float, w: float, h: float,
         fill_color: str = C_WHITE, stroke_color: str = C_MGRAY,
         line_width: float = 0.5) -> None:
    from reportlab.lib.colors import HexColor
    c.setFillColor(HexColor(fill_color))
    c.setStrokeColor(HexColor(stroke_color))
    c.setLineWidth(line_width)
    c.rect(x, y, w, h, fill=1, stroke=1)


def _section_label(c, x: float, y: float, text: str) -> None:
    """Small uppercase section heading."""
    from reportlab.lib.colors import HexColor
    c.setFont("Helvetica-Bold", 7)
    c.setFillColor(HexColor(C_NAVY))
    c.drawString(x, y, text.upper())


def _kv(c, x: float, y: float, label: str, value: str,
        label_w: float = 80, value_color: str = C_BLACK) -> None:
    from reportlab.lib.colors import HexColor
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor(C_DGRAY))
    c.drawString(x, y, label)
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(HexColor(value_color))
    c.drawString(x + label_w, y, str(value))


# ── Page 1 drawing functions ──────────────────────────────────────────────────

def _draw_patient_block(c, patient, procedure: str, y_top: float) -> None:
    """Patient info box — top-left."""
    from reportlab.lib.colors import HexColor
    bw, bh = CONTENT_W * 0.48, 88
    bx, by = MARGIN_L, y_top - bh
    _box(c, bx, by, bw, bh)
    _section_label(c, bx + 8, by + bh - 14, "Patient / Case")

    case_id   = patient.patient_id or "—"
    date      = patient.study_date or datetime.now().strftime("%Y-%m-%d")
    surgeon   = patient.referring_physician or "—"
    facility  = patient.institution or "—"

    row_h = 14
    rows = [
        ("Case ID",    case_id),
        ("Procedure",  procedure),
        ("Date",       date),
        ("Surgeon",    surgeon),
        ("Facility",   facility),
    ]
    for i, (lbl, val) in enumerate(rows):
        ry = by + bh - 26 - i * row_h
        _kv(c, bx + 8, ry, lbl + ":", val, label_w=58)


def _draw_alignment_block(c, spinopelvic: dict, y_top: float) -> None:
    """Alignment parameters box — top-right."""
    from reportlab.lib.colors import HexColor
    bw, bh = CONTENT_W * 0.48, 88
    bx = MARGIN_L + CONTENT_W - bw
    by = y_top - bh
    _box(c, bx, by, bw, bh)
    _section_label(c, bx + 8, by + bh - 14, "Alignment Parameters")

    pi   = spinopelvic.get("pelvic_incidence_deg",  spinopelvic.get("PI",  0.0))
    pt   = spinopelvic.get("pelvic_tilt_deg",       spinopelvic.get("PT",  0.0))
    ss   = spinopelvic.get("sacral_slope_deg",       spinopelvic.get("SS",  0.0))
    ll   = spinopelvic.get("lumbar_lordosis_deg",    spinopelvic.get("LL",  0.0))
    sva  = spinopelvic.get("sva_mm",                spinopelvic.get("SVA", 0.0))
    pill = spinopelvic.get("pi_ll_mismatch_deg",    spinopelvic.get("PI_LL", round(float(pi) - float(ll), 1)))

    pill_val = float(pill)
    status_text  = "ACCEPTABLE" if abs(pill_val) <= 10 else "REVIEW NEEDED"
    status_color = C_TEAL if abs(pill_val) <= 10 else C_AMBER

    col_w = bw / 2 - 8
    params_l = [("PI", f"{pi:.0f}°"), ("SS", f"{ss:.0f}°"), ("SVA", f"{sva:.0f} mm")]
    params_r = [("PT", f"{pt:.0f}°"), ("LL", f"{ll:.0f}°"), ("PI-LL", f"{pill_val:+.0f}°")]

    row_h = 13
    for i, (lbl, val) in enumerate(params_l):
        ry = by + bh - 28 - i * row_h
        _kv(c, bx + 8, ry, lbl + ":", val, label_w=34)

    for i, (lbl, val) in enumerate(params_r):
        ry = by + bh - 28 - i * row_h
        _kv(c, bx + 8 + col_w, ry, lbl + ":", val, label_w=40)

    # Status badge
    badge_y = by + 9
    badge_w = bw - 16
    c.setFillColor(HexColor(status_color))
    c.roundRect(bx + 8, badge_y, badge_w, 16, 3, fill=1, stroke=0)
    c.setFillColor(HexColor(C_WHITE))
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(bx + 8 + badge_w / 2, badge_y + 5, f"Status: {status_text}")


def _draw_render_image(c, render_image: np.ndarray, y_top: float, y_bottom: float) -> None:
    """Embed the 3-D spine render, right-aligned, scaled to fit the available space."""
    from reportlab.lib.utils import ImageReader
    from reportlab.lib.colors import HexColor

    max_w_pt = CONTENT_W * 0.42
    max_h_pt = y_top - y_bottom

    # Convert numpy HxWx3 → PIL → PNG bytes
    from PIL import Image as PILImage
    arr = render_image
    if arr.dtype != np.uint8:
        arr = (np.clip(arr, 0, 1) * 255).astype(np.uint8)
    pil = PILImage.fromarray(arr)

    ih, iw = arr.shape[:2]
    scale = min(max_w_pt / iw, max_h_pt / ih)
    draw_w = iw * scale
    draw_h = ih * scale

    buf = io.BytesIO()
    pil.save(buf, format="PNG")
    buf.seek(0)

    ix = MARGIN_L + CONTENT_W - draw_w
    iy = y_bottom + (max_h_pt - draw_h) / 2
    c.drawImage(ImageReader(buf), ix, iy, width=draw_w, height=draw_h,
                mask="auto", preserveAspectRatio=True)


def _draw_implant_table(c, plan, y_top: float) -> float:
    """
    Draw the implant table. Returns the y coordinate of the bottom edge.
    Columns: Level | Side | Diameter | Length | Backup Sizes
    """
    from reportlab.lib.colors import HexColor

    col_x  = [MARGIN_L, MARGIN_L+70, MARGIN_L+130, MARGIN_L+200, MARGIN_L+270]
    col_w  = [70, 60, 70, 70, CONTENT_W - 270]
    hdrs   = ["Level", "Side", "Diameter", "Length", "Backup Sizes"]
    row_h  = 15
    hdr_h  = 18

    # Header row
    c.setFillColor(HexColor(C_NAVY))
    c.rect(MARGIN_L, y_top - hdr_h, CONTENT_W, hdr_h, fill=1, stroke=0)
    c.setFillColor(HexColor(C_WHITE))
    c.setFont("Helvetica-Bold", 8)
    for cx, hdr in zip(col_x, hdrs):
        c.drawString(cx + 4, y_top - hdr_h + 5, hdr)

    y = y_top - hdr_h
    screws = sorted(plan.screws.items())
    for i, (key, screw) in enumerate(screws):
        row_y = y - row_h * (i + 1)
        # Alternating shading
        if i % 2 == 0:
            c.setFillColor(HexColor(C_LGRAY))
            c.rect(MARGIN_L, row_y, CONTENT_W, row_h, fill=1, stroke=0)

        # Warning highlight
        has_warn = any(screw.level in w for w in plan.warnings)
        txt_color = HexColor(C_AMBER) if has_warn else HexColor(C_BLACK)

        side  = "Right" if key.endswith("right") else "Left"
        backs = plan.backup_screws.get(key, [])
        back_str = ", ".join(f"{b.diameter_mm}x{b.length_mm}" for b in backs) or "—"
        vals  = [screw.level, side,
                 f"{screw.diameter_mm} mm", f"{screw.length_mm} mm", back_str]

        c.setFont("Helvetica", 8)
        c.setFillColor(txt_color)
        for cx, val in zip(col_x, vals):
            c.drawString(cx + 4, row_y + 4, val)

    # Border around whole table
    total_h = hdr_h + row_h * len(screws)
    c.setStrokeColor(HexColor(C_MGRAY))
    c.setLineWidth(0.5)
    c.rect(MARGIN_L, y_top - total_h, CONTENT_W, total_h, fill=0, stroke=1)

    return y_top - total_h


def _draw_rod_box(c, plan, y_top: float) -> None:
    """Rod specification summary bar."""
    from reportlab.lib.colors import HexColor
    bh = 40
    _box(c, MARGIN_L, y_top - bh, CONTENT_W, bh, fill_color="#EEF2FF")
    _section_label(c, MARGIN_L + 8, y_top - 13, "Rod Specification")

    specs = [
        ("Length",     f"{plan.rod_length_mm:.0f} mm"),
        ("Curvature",  f"{plan.rod_curvature_deg:.1f}°"),
        ("Material",   plan.rod_material),
        ("Construct",  "Bilateral"),
    ]
    col_w = CONTENT_W / len(specs)
    for i, (lbl, val) in enumerate(specs):
        cx = MARGIN_L + i * col_w + 8
        c.setFont("Helvetica", 7)
        c.setFillColor(HexColor(C_DGRAY))
        c.drawString(cx, y_top - 23, lbl)
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(HexColor(C_NAVY))
        c.drawString(cx, y_top - 35, val)


# ── Page 2 drawing functions ──────────────────────────────────────────────────

def _draw_tray_summary(c, tray, y_top: float) -> None:
    """Tray optimisation summary boxes."""
    from reportlab.lib.colors import HexColor
    bh = 70
    col_w = CONTENT_W / 4
    labels = [
        ("Standard Tray",  str(tray.standard_baseline) + " implants", C_BLACK),
        ("Optimized Tray", str(tray.total_implants) + " implants",    C_NAVY),
        ("Reduction",      f"{tray.reduction_pct:.0f}%",
         C_TEAL if tray.reduction_pct >= 20 else C_AMBER),
        ("Est. Savings",   f"${tray.standard_baseline * 2.50 - tray.estimated_sterilization_cost_usd:.0f}",
         C_TEAL),
    ]
    for i, (title, value, vc) in enumerate(labels):
        bx = MARGIN_L + i * col_w
        _box(c, bx, y_top - bh, col_w - 4, bh)
        c.setFont("Helvetica", 7)
        c.setFillColor(HexColor(C_DGRAY))
        c.drawCentredString(bx + (col_w - 4) / 2, y_top - 18, title)
        c.setFont("Helvetica-Bold", 20)
        c.setFillColor(HexColor(vc))
        c.drawCentredString(bx + (col_w - 4) / 2, y_top - 46, value)
        # Teal bottom accent for highlight metrics
        if vc == C_TEAL:
            c.setFillColor(HexColor(C_TEAL))
            c.rect(bx, y_top - bh, col_w - 4, 4, fill=1, stroke=0)


def _draw_tray_table(c, tray, y_top: float) -> float:
    """Compact tray contents table. Returns bottom y."""
    from reportlab.lib.colors import HexColor
    col_x = [MARGIN_L, MARGIN_L+110, MARGIN_L+210, MARGIN_L+280, MARGIN_L+360]
    hdrs  = ["Diameter", "Length", "Qty", "Role", "Notes"]
    row_h = 14
    hdr_h = 17

    c.setFillColor(HexColor(C_NAVY))
    c.rect(MARGIN_L, y_top - hdr_h, CONTENT_W, hdr_h, fill=1, stroke=0)
    c.setFillColor(HexColor(C_WHITE))
    c.setFont("Helvetica-Bold", 8)
    for cx, hdr in zip(col_x, hdrs):
        c.drawString(cx + 4, y_top - hdr_h + 4, hdr)

    y = y_top - hdr_h
    for i, item in enumerate(sorted(tray.items, key=lambda x: (x.diameter_mm, x.length_mm))):
        ry = y - row_h * (i + 1)
        if i % 2 == 0:
            c.setFillColor(HexColor(C_LGRAY))
            c.rect(MARGIN_L, ry, CONTENT_W, row_h, fill=1, stroke=0)
        role_color = C_TEAL if "primary" in item.role else C_DGRAY
        vals = [f"{item.diameter_mm} mm", f"{item.length_mm} mm",
                str(item.quantity), item.role, ""]
        c.setFont("Helvetica", 8)
        for j, (cx, val) in enumerate(zip(col_x, vals)):
            c.setFillColor(HexColor(role_color if j == 3 else C_BLACK))
            c.drawString(cx + 4, ry + 3, val)

    total_h = hdr_h + row_h * len(tray.items)
    c.setStrokeColor(HexColor(C_MGRAY))
    c.setLineWidth(0.5)
    c.rect(MARGIN_L, y_top - total_h, CONTENT_W, total_h, fill=0, stroke=1)
    return y_top - total_h


def _draw_checklist(c, y_top: float) -> None:
    """Pre-printed logistics checklist with empty checkboxes."""
    from reportlab.lib.colors import HexColor

    items = [
        "Plan reviewed by surgeon",
        "Tray pulled and verified by rep",
        "Backup sizes confirmed available",
        "Alignment parameters reviewed with surgical team",
        "OR schedule confirmed",
    ]
    _section_label(c, MARGIN_L, y_top - 2, "Pre-Operative Logistics Checklist")

    row_h = 24
    for i, text in enumerate(items):
        ry = y_top - 18 - i * row_h
        # Checkbox
        c.setStrokeColor(HexColor(C_NAVY))
        c.setLineWidth(1.0)
        c.rect(MARGIN_L, ry, 12, 12, fill=0, stroke=1)
        # Label
        c.setFont("Helvetica", 10)
        c.setFillColor(HexColor(C_BLACK))
        c.drawString(MARGIN_L + 20, ry + 2, text)
        # Light rule
        c.setStrokeColor(HexColor(C_LGRAY))
        c.setLineWidth(0.3)
        c.line(MARGIN_L, ry - 4, MARGIN_L + CONTENT_W, ry - 4)

    # Signature lines
    sig_y = y_top - 18 - len(items) * row_h - 20
    for label in ("Surgeon sign-off:", "Rep sign-off:"):
        c.setFont("Helvetica", 8)
        c.setFillColor(HexColor(C_DGRAY))
        c.drawString(MARGIN_L, sig_y, label)
        c.setStrokeColor(HexColor(C_MGRAY))
        c.setLineWidth(0.5)
        c.line(MARGIN_L + 90, sig_y + 2, MARGIN_L + 250, sig_y + 2)
        sig_y -= 22


# ── Public API ────────────────────────────────────────────────────────────────

def generate_plan(
    patient,                            # spineoptimizer.core.models.PatientInfo
    implant_plan,                       # src.dragonfly.implant_predictor.ImplantPlan
    tray_config,                        # src.dragonfly.tray_optimizer.TrayConfiguration
    spinopelvic: dict,
    render_image: Optional[np.ndarray],
    output_path: Path,
    procedure: str = "Lumbar Fusion",
    anonymise: bool = False,
) -> Path:
    """
    Generate the 2-page Dragonfly Spine pre-operative plan PDF.

    Parameters
    ----------
    patient       : PatientInfo — name / ID / surgeon / facility
    implant_plan  : ImplantPlan — screws, rods, confidence values
    tray_config   : TrayConfiguration — optimised tray items + reduction
    spinopelvic   : dict — PI, PT, SS, LL, SVA, PI-LL keys
    render_image  : numpy uint8 HxWx3 or None — 3-D spine render from BoneRenderer
    output_path   : destination .pdf path
    procedure     : procedure name string (default "Lumbar Fusion")
    anonymise     : if True, replace name/ID with "Anonymous / CASE-XXXX"

    Returns
    -------
    Path to the written PDF.
    """
    rl_canvas, HexColor = _rl()
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Anonymise if requested
    if anonymise:
        patient.name = "Anonymous"
        patient.patient_id = f"CASE-{hash(patient.patient_id) % 9999:04d}"

    case_id = patient.patient_id or "N/A"

    c = rl_canvas.Canvas(str(output_path), pagesize=(PAGE_W, PAGE_H))
    c.setTitle("surgeon-sim — Pre-Operative Surgical Plan")
    c.setAuthor("surgeon-sim")
    c.setSubject(f"Pre-Operative Plan — Case {case_id}")

    # ──────────────────────────────────────────────────────────────────────────
    # PAGE 1 — SURGICAL PLAN
    # ──────────────────────────────────────────────────────────────────────────
    _header_band(c)

    top_y = PAGE_H - 44 - 8

    # Patient block (left) and alignment box (right)
    _draw_patient_block(c, patient, procedure, top_y)
    _draw_alignment_block(c, spinopelvic, top_y)

    # 3D render area (right-aligned, between patient row and implant table)
    patient_bottom = top_y - 88 - 8
    n_screws   = len(implant_plan.screws)
    table_h    = 18 + n_screws * 15 + 4
    rod_h      = 40 + 8
    footer_h   = MARGIN_B + 38
    table_top  = footer_h + rod_h + table_h
    render_top = patient_bottom - 6

    if render_image is not None:
        try:
            _draw_render_image(c, render_image, render_top, table_top + 4)
        except Exception as exc:
            log.warning("Could not embed render image: %s", exc)

    # Implant table
    implant_section_label_y = table_top + table_h + 2
    from reportlab.lib.colors import HexColor as HC
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(HC(C_NAVY))
    c.drawString(MARGIN_L, implant_section_label_y, "IMPLANT PLAN")
    table_bottom = _draw_implant_table(c, implant_plan, table_top + table_h)

    # Rod specification
    rod_top = table_bottom - 6
    _draw_rod_box(c, implant_plan, rod_top)

    # Warnings (if any)
    if implant_plan.warnings:
        wy = rod_top - 40 - 6
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(HC(C_AMBER))
        c.drawString(MARGIN_L, wy + 12, "CLINICAL NOTICES")
        c.setFont("Helvetica", 7)
        for w in implant_plan.warnings[:3]:
            c.drawString(MARGIN_L + 8, wy, f"• {w}")
            wy -= 10

    _footer(c, case_id, 1)
    c.showPage()

    # ──────────────────────────────────────────────────────────────────────────
    # PAGE 2 — LOGISTICS CHECKLIST
    # ──────────────────────────────────────────────────────────────────────────
    _header_band(c, title_right="Logistics Checklist")

    top2 = PAGE_H - 44 - 12

    # Section: Tray summary
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(HC(C_NAVY))
    c.drawString(MARGIN_L, top2, "TRAY OPTIMISATION SUMMARY")
    _draw_tray_summary(c, tray_config, top2 - 4)

    # Section: Tray contents
    tray_top = top2 - 4 - 70 - 14
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(HC(C_NAVY))
    c.drawString(MARGIN_L, tray_top, "TRAY CONTENTS")
    tray_bottom = _draw_tray_table(c, tray_config, tray_top - 4)

    # Rod specs on page 2
    rod2_top = tray_bottom - 8
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(HC(C_NAVY))
    c.drawString(MARGIN_L, rod2_top, "ROD SPECIFICATION")
    _draw_rod_box(c, implant_plan, rod2_top - 4)

    # Section: Checklist
    check_top = rod2_top - 4 - 40 - 14
    _draw_checklist(c, check_top)

    _footer(c, case_id, 2)
    c.showPage()

    c.save()
    log.info("Surgical plan PDF written: %s", output_path)
    return output_path
