using System;
using System.IO;
using System.Threading.Tasks;
using Dragonfly.XR.Domain;
using UnityEngine;

namespace Dragonfly.XR.Simulation
{
    // Replays neutral instrument trajectory JSON generated by Python tooling
    // or offline simulators such as ORBIT-Surgical. Coordinates are exported
    // in millimetres and converted to Unity metres at the replay target.
    public class InstrumentTrajectoryReplay : MonoBehaviour
    {
        [Tooltip("Transform moved by the trajectory. Defaults to this transform.")]
        public Transform Target;

        [Tooltip("Replay automatically after LoadTrajectoryAsync succeeds.")]
        public bool PlayOnLoad = true;

        [Tooltip("Loop after the last sample.")]
        public bool Loop;

        [Tooltip("Scale exported millimetres into Unity metres.")]
        public float MillimetresToUnity = 0.001f;

        [Tooltip("Optional parent transform for case-local coordinates.")]
        public Transform CaseFrame;

        public InstrumentTrajectory Trajectory { get; private set; }
        public float Gripper { get; private set; }
        public string ContactState { get; private set; } = "free";
        public bool IsPlaying { get; private set; }

        public event Action<InstrumentPoseSample> OnSampleApplied;

        float _time;

        void Awake()
        {
            if (Target == null) Target = transform;
        }

        void Update()
        {
            if (!IsPlaying || Trajectory == null || !Trajectory.IsValid) return;

            _time += Time.deltaTime;
            var duration = Trajectory.DurationSeconds;
            if (_time > duration)
            {
                if (!Loop)
                {
                    _time = duration;
                    IsPlaying = false;
                }
                else if (duration > 0f)
                {
                    _time %= duration;
                }
            }

            ApplyAtTime(_time);
        }

        public async Task<bool> LoadTrajectoryAsync(string jsonPathAbsolute)
        {
            if (!File.Exists(jsonPathAbsolute))
            {
                Debug.LogError($"[InstrumentTrajectoryReplay] missing trajectory JSON: {jsonPathAbsolute}");
                return false;
            }

            var json = await File.ReadAllTextAsync(jsonPathAbsolute);
            return LoadTrajectoryJson(json, jsonPathAbsolute);
        }

        /// <summary>
        /// Load JSON under Assets/StreamingAssets (relative path, e.g. trajectories/demo_needle_lift.json).
        /// Editor and standalone builds resolve this with File APIs.
        /// Quest/Android StreamingAssets often require UnityWebRequest; use disk paths or Addressables there instead.
        /// </summary>
        public Task<bool> LoadTrajectoryStreamingAssetsRelativeAsync(string relativePath)
        {
#if UNITY_EDITOR || UNITY_STANDALONE
            var abs = Path.Combine(Application.streamingAssetsPath, relativePath);
            return LoadTrajectoryAsync(abs);
#else
            Debug.LogWarning(
                "[InstrumentTrajectoryReplay] StreamingAssets disk load is not wired for this platform; " +
                "copy JSON to persistent storage or use Addressables.");
            return Task.FromResult(false);
#endif
        }

        public bool LoadTrajectoryJson(string json, string label = "trajectory JSON")
        {
            Trajectory = JsonUtility.FromJson<InstrumentTrajectory>(json);
            if (Trajectory == null || !Trajectory.IsValid)
            {
                Debug.LogError($"[InstrumentTrajectoryReplay] failed to parse {label}");
                return false;
            }

            ValidateSampleOrder();
            _time = 0f;
            ApplyAtTime(0f);
            if (PlayOnLoad) Play();

            Debug.Log(
                $"[InstrumentTrajectoryReplay] loaded {Trajectory.trajectory_id} " +
                $"instrument={Trajectory.instrument_id} samples={Trajectory.samples.Count}");
            return true;
        }

        public void Play()
        {
            if (Trajectory == null || !Trajectory.IsValid) return;
            IsPlaying = true;
        }

        public void Pause() => IsPlaying = false;

        public void Stop()
        {
            IsPlaying = false;
            _time = 0f;
            if (Trajectory != null && Trajectory.IsValid) ApplyAtTime(0f);
        }

        public void ApplyAtTime(float timeSeconds)
        {
            if (Trajectory == null || !Trajectory.IsValid) return;
            var samples = Trajectory.samples;

            if (timeSeconds <= samples[0].timestamp_s)
            {
                ApplySample(samples[0]);
                return;
            }

            for (int i = 0; i < samples.Count - 1; i++)
            {
                var a = samples[i];
                var b = samples[i + 1];
                if (timeSeconds > b.timestamp_s) continue;

                var span = Mathf.Max(0.0001f, b.timestamp_s - a.timestamp_s);
                var t = Mathf.Clamp01((timeSeconds - a.timestamp_s) / span);
                ApplyInterpolated(a, b, t);
                return;
            }

            ApplySample(samples[^1]);
        }

        void ApplyInterpolated(InstrumentPoseSample a, InstrumentPoseSample b, float t)
        {
            var localPosMm = Vector3.Lerp(a.PositionMm, b.PositionMm, t);
            var localRot = Quaternion.Slerp(a.Rotation, b.Rotation, t);
            var sample = t < 0.5f ? a : b;

            ApplyPose(localPosMm, localRot);
            Gripper = Mathf.Lerp(a.gripper, b.gripper, t);
            ContactState = sample.contact_state;
            OnSampleApplied?.Invoke(sample);
        }

        void ApplySample(InstrumentPoseSample sample)
        {
            ApplyPose(sample.PositionMm, sample.Rotation);
            Gripper = sample.gripper;
            ContactState = sample.contact_state;
            OnSampleApplied?.Invoke(sample);
        }

        void ApplyPose(Vector3 localPosMm, Quaternion localRot)
        {
            var localPos = localPosMm * MillimetresToUnity;
            if (CaseFrame != null)
            {
                Target.SetPositionAndRotation(
                    CaseFrame.TransformPoint(localPos),
                    CaseFrame.rotation * localRot);
            }
            else
            {
                Target.SetLocalPositionAndRotation(localPos, localRot);
            }
        }

        void ValidateSampleOrder()
        {
            var previous = -1f;
            foreach (var sample in Trajectory.samples)
            {
                if (sample.timestamp_s <= previous)
                {
                    Debug.LogWarning(
                        "[InstrumentTrajectoryReplay] samples are not strictly " +
                        "increasing; replay may jump");
                    return;
                }
                previous = sample.timestamp_s;
            }
        }
    }
}

