"""
Regenerate unity/Assets/Resources/implant_catalog.json from the canonical
dragonfly catalog.

Usage:
    python tools/port_catalog.py /path/to/dragonfly/spineoptimizer

Indications are written as integer indices into the C# SpineLevel enum to
keep the JSON small and avoid Unity JsonUtility's missing string-enum support.
The order MUST match Domain/SpineLevel.cs:
    0 C3_C4   1 C4_C5   2 C5_C6   3 C6_C7
    4 L1_L2   5 L2_L3   6 L3_L4   7 L4_L5   8 L5_S1
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

LEVEL_INDEX = {
    "C3-C4": 0, "C4-C5": 1, "C5-C6": 2, "C6-C7": 3,
    "L1-L2": 4, "L2-L3": 5, "L3-L4": 6, "L4-L5": 7, "L5-S1": 8,
}
TYPE_INDEX = {"lumbar_tdr": 0, "cervical_tdr": 1}


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    spineoptimizer = Path(sys.argv[1]).resolve()
    sys.path.insert(0, str(spineoptimizer.parent))
    from spineoptimizer.core.catalog import FULL_CATALOG  # type: ignore

    implants = []
    for imp in FULL_CATALOG:
        implants.append({
            "ImplantId": imp.implant_id,
            "Manufacturer": imp.manufacturer,
            "ProductName": imp.product_name,
            "ImplantType": TYPE_INDEX[imp.implant_type.value],
            "ApDepthMm": imp.ap_depth_mm,
            "MlWidthMm": imp.ml_width_mm,
            "HeightMm": imp.height_mm,
            "HeightMinMm": imp.height_min_mm,
            "HeightMaxMm": imp.height_max_mm,
            "LordoticAngleDeg": imp.lordotic_angle_deg,
            "AvailableAnglesDeg": list(imp.available_angles_deg),
            "MaterialEndplate": imp.material_endplate,
            "MaterialCore": imp.material_core,
            "HasKeel": imp.has_keel,
            "KeelHeightMm": imp.keel_height_mm,
            "FdaCleared": imp.fda_cleared,
            "CeMarked": imp.ce_marked,
            "Indications": [LEVEL_INDEX[lvl.value] for lvl in imp.indications],
        })

    out = Path(__file__).parent.parent / "unity" / "Assets" / "Resources" / "implant_catalog.json"
    payload = {
        "_comment": "Generated by tools/port_catalog.py — do not hand-edit. "
                    "Regenerate from dragonfly/spineoptimizer/core/catalog.py.",
        "implants": implants,
    }
    out.write_text(json.dumps(payload, indent=2))
    print(f"Wrote {len(implants)} implants → {out}")


if __name__ == "__main__":
    main()
